# config
cover: https://i.loli.net/2018/08/06/5b67cf0fe9eac.jpeg
#cover: //blog.ghost.org/content/images/2013/Nov/cover.png
logo: https://i.loli.net/2018/08/05/5b66ab53bcdfc.jpg
#logo: //blog.ghost.org/content/images/2013/Nov/bloglogo_1-1.png
bio: 'A young developer, Likes coding, sleeping and eating. Also a senior high student in Jiangning, Nanjing, Jiangsu,China.'

# Content
excerpt_link: "[Read article]"

# Miscellaneous
rss: /atom.xml

#Mathjax support
mathjax:
  enable: true
  per_page: true
