# config
cover: https://i.loli.net/2018/08/06/5b67cf0fe9eac.jpeg
logo: https://i.loli.net/2018/08/05/5b66ab53bcdfc.jpg
bio: 'A young developer, Likes coding, sleeping and eating. Also a senior high student in Jiangning, Nanjing, Jiangsu,China.'
<<<<<<< HEAD

# Content
excerpt_link: "[Read article]"
=======


# Content
excerpt_link: "[Read article]"

>>>>>>> master

# Miscellaneous
rss: /atom.xml

<<<<<<< HEAD
=======

>>>>>>> master
#Mathjax support
mathjax:
  enable: true
  per_page: true
<<<<<<< HEAD
=======

 
#PS: Here's a good Image Hosting Website
#IHW: https://sm.ms
  #Warning: Please do NOT upload R-18 Pictures
>>>>>>> master
